config/routes.rb
Rails.application.routes.draw do
  resources :speeches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :speeches do
      end
    end
  end

  if Rails.env.development?
    get "/storage/*path" => "active_storage/disk#show"
  end

  get 'speeches/day/1', to: 'speeches#day_one', as: 'day_one_speeches'
  get 'speeches/day/2', to: 'speeches#day_two', as: 'day_two_speeches'
  # Defines the root path route ("/")
  # root "posts#index"
  root "speeches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/speech.rb
class Speech < ApplicationRecord
  has_one_attached :upload
  
  attribute :time, :datetime
  def start_time
    time.strftime("%H:%M:%S") if time.present?
  end

  def end_time
    time.strftime("%H:%M:%S") if time.present?
  end

  def as_json(options = {})
    super(options.merge(except: [:created_at, :updated_at], methods: [:upload_url]))
  end
  
  def upload_url
    upload.url if upload.attached?
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/v1/speeches_controller.rb
module Api
  module V1
    class SpeechesController < ApplicationController
      def index
        @speeches = Speech.all 

        ActiveStorage::Current.url_options = { host: request.base_url }

   
        day_one_date = Date.parse('2023-10-16')
        day_two_date = Date.parse('2023-10-17')

        morning_start_time = '09:00:00'
        afternoon_start_time = '13:00:00'
      
        @day_one_morning_speeches = []
        @day_one_afternoon_speeches = []
        @day_two_morning_speeches = []
        @day_two_afternoon_speeches = []
      
        @speeches.each do |speech|
          if speech.try!(:time)
            if speech.time.to_date == day_one_date
              if speech.time.strftime('%H:%M:%S') >= morning_start_time && speech.time.strftime('%H:%M:%S') < afternoon_start_time
                @day_one_morning_speeches << speech
              else
                @day_one_afternoon_speeches << speech
              end
            elsif speech.time.to_date == day_two_date
              if speech.time.strftime('%H:%M:%S') >= morning_start_time && speech.time.strftime('%H:%M:%S') < afternoon_start_time
                @day_two_morning_speeches << speech
              else
                @day_two_afternoon_speeches << speech
              end
            end
          end
        end
      
        render json: {
          day_one: {
            morning_speeches: @day_one_morning_speeches,
            afternoon_speeches: @day_one_afternoon_speeches
          },
          day_two: {
            morning_speeches: @day_two_morning_speeches,
            afternoon_speeches: @day_two_afternoon_speeches
          }
        }
      end
      
      private

      def day_one_date
        Date.parse('2023-10-16') 
      end

      def day_two_date
        Date.parse('2023-10-17') 
      end

      def morning_start_time
        '09:00:00' 
      end

      def afternoon_start_time
        '13:00:00' 
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController
  before_action :set_speech, only: %i[ show edit update destroy ]

  # GET /speeches or /speeches.json
  def index
    @speeches = Speech.order('time ASC').all
  end

  # GET /speeches/1 or /speeches/1.json
  def show
  end

  # GET /speeches/new
  def new
    @speech = Speech.new
  end

  # GET /speeches/1/edit
  def edit
  end

  # POST /speeches or /speeches.json
  def create
    @speech = Speech.new(speech_params)

    respond_to do |format|
      if @speech.save
        format.html { redirect_to speech_url(@speech), notice: "Speech was successfully created." }
        format.json { render :show, status: :created, location: @speech }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speeches/1 or /speeches/1.json
  def update
    respond_to do |format|
      if @speech.update(speech_params)
        format.html { redirect_to speech_url(@speech), notice: "Speech was successfully updated." }
        format.json { render :show, status: :ok, location: @speech }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speeches/1 or /speeches/1.json
  def destroy
    @speech.destroy!

    respond_to do |format|
      format.html { redirect_to speeches_url, notice: "Speech was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    # GET /speeches/day/1
  def day_one
    @day_one_speeches = Speech.where("time >= ? AND time < ?", Date.parse('2023-10-16').beginning_of_day, Date.parse('2023-10-16').end_of_day)
  end
  
    # GET /speeches/day/2
  def day_two
    @day_two_speeches = Speech.where("time >= ? AND time < ?", Date.parse('2023-10-17').beginning_of_day, Date.parse('2023-10-17').end_of_day)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speech
      @speech = Speech.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def speech_params
      params.require(:speech).permit(:description, :time, :hour, :upload)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lecture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/speeches/_form.html.erb
<%= simple_form_for @speech do |form| %>
  <% if speech.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(speech.errors.count, "error") %> prohibited this speech from being saved:</h2>

      <ul>
        <% speech.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.input :description, as: :text %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.input :time  %>
  </div>

  <div>
    <%= form.label :hour, style: "display: block" %>
    <%= form.input :hour %>
  </div>
  <div><%= form.file_field :upload %></div>
  <p>
  <div>
  <%= form.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/speeches/_speech.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 mb-3 mb-sm-0">
      <div id="<%= dom_id speech %>">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
          
            <h3 class="card-title">Description</h3>
            <p class="card-text"> <%= speech.description %></p>
            <h3 class="card-title">Time</h3>
            <p class="card-text"> <%= speech.time %></p>
            <h3 class="card-title">Hour</h3>
            <p class="card-text"> <%= speech.hour %></p>
            <a href="#" class="btn btn-primary">Download</a>
            <%= link_to "Detalhes", speech, class: "btn btn-secondary" %>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/speeches/edit.html.erb
<h1>Editing speech</h1>

<%= render "form", speech: @speech %>

<br>

<div>
  <%= link_to "datelhes", @speech, class: "btn btn-secondary" %> 
  <%= link_to "voltar", speeches_path, class: "btn btn-success" %>
</div>

app/views/speeches/index.html.erb
<h1>Lista de Palestras</h1>

<table class="table">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Data</th>
      <th>Hora</th>
      <th>Tempo</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @speeches.each do |speech| %>
      <tr>
        <td><%= speech.description %></td>
        <td><%= speech.time ? speech.time.strftime("%Y-%m-%d") : "Data não disponível" %></td>
        <td><%= speech.time ? speech.time.strftime("%H:%M:%S") : "Hora não disponível" %></td>
        <td><%= speech.hour %></td>
        <td>
          <%= link_to "Detalhes", speech, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<div class="container text-center">
  <div class="row align-items-start">
    <div class="col">
    <%= link_to "Cadastrar palestra", new_speech_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/speeches/new.html.erb
<h1>New speech</h1>

<%= render "form", speech: @speech %>

<br>

<div>
  <%= link_to "Voltar", speeches_path, class:"btn btn-dark" %>
</div>

app/views/speeches/show.html.erb
<h1>Detalhes da Palestra</h1>

<div class="card">
  <div class="card-body">
    <h3 class="card-title">Descrição</h3>
    <p class="card-text"><%= @speech.description %></p>

    <h3 class="card-title">Data</h3>
    <p class="card-text"><%= @speech.time.strftime("%Y-%m-%d") %></p>

    <h3 class="card-title">Hora</h3>
    <p class="card-text"><%= @speech.hour %></p>
    <% if @speech.upload.attached? %>
    <p> <%= link_to 'Baixar Arquivo', rails_blob_path(@speech.upload, disposition: 'attachment'), class: "btn btn-success"%></p>
    <% end %>


    <%= link_to "Voltar à Lista", speeches_path, class: "btn btn-secondary" %>
    <%= link_to "Edit this speech", edit_speech_path(@speech), class:"btn btn-warning"  %>
  </div>
</div>